apiVersion: v1
kind: Service
metadata:
  name: {{ include "sap-cc.fullname" . }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "PrivateSubnet"
  labels:
    {{- include "sap-cc.labels" . | nindent 4 }}
spec:
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sap-cc.selectorLabels" . | nindent 4 }}
