name: Bump Version and Tag

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Bump the chart version
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        docker run --rm -v "$PWD":/app treeder/bump --filename helm/sap-cc/Chart.yaml
        git commit -m "bumped version" helm/sap-cc/Chart.yaml
        oldv=$(git tag --sort=-v:refname --list "v[0-9]*" | head -n 1)
        echo "old version: $oldv"
        export NEWV=$(docker run --rm -v "$PWD":/app treeder/bump --input "$oldv" patch)

     - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ env.NEWV }}

      - name: Commit push and tag 
        run: |
          git push
          git tag -a ${{ env.NEWV }} -m "version ${{ env.NEWV }}"
          git push --follow-tags
